apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: him81bc5k-python
  janus-idp.io/tekton: him81bc5k-python
  backstage.io/kubernetes-id: him81bc5k-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: him81bc5k-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
